@MinimalApi_HostAddress = https://localhost:7065

GET {{MinimalApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MinimalApi_HostAddress}}/AddItem
Content-Type: application/json

{
  "Title":"Example",
  "IsCompleted":false
}

###
